[build]
  command = "cd ai-trainer && npm run build"
  publish = "ai-trainer/out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 